name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        board:
          - jetson-nano
          - jetson-nano-2gb
          - jetson-orin-nano
    uses: ./.github/workflows/_build.yml
    with:
      board: ${{ matrix.board }}
      compress: true
      release: true
